apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oz7wkpsjp-python
  janus-idp.io/tekton: oz7wkpsjp-python
  backstage.io/kubernetes-id: oz7wkpsjp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oz7wkpsjp-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
